### ISSUE TITLE
Minimized on click

### ISSUE THREAD

**Issue by gilcu2** [glenreesor/HammerBar#1]
Hi, in v0.9. when I click the app button it gets minimize, so I always need to click 2 times. How can I solve it?
Also, how can I run the dev version?
Thanks
Reynaldo

**Comment by glenreesor** [comment]
I missed your second question about how to run the dev version :smile: . HammerBar is written in typescript and gets transpiled to Lua using [TypeScriptToLua](https://typescripttolua.github.io/) . You can build that by cloning this repo, installing `npm`, running `npm install`, and then running `npm build`. The transpiled lua will be in the `build/` directory.

Unfortunately the dev version has a slightly different interface that isn't documented yet, and requires hard-coding in `init.ts`. I'm hoping to get a prerelease ready soon though!
