### ISSUE TITLE
Some Adobe Programs not showing up in Hammerbar

### ISSUE THREAD

**Issue by daveedmee** [glenreesor/HammerBar#2]
Premiere Pro, After Effects & Media Encoder don't show up in Hammerbar. Haven't tested with others yet

**Comment by glenreesor** [comment]
Hi daveedmee thanks for reaching out. I suspect this is related to a bug in Hammerspoon (the toolkit used by HammerBar) -- I've also encountered this with LibreOffice and the only thing that has worked is to:
- start the program (LibreOffice for me or Premiere Pro for you)
- focus a different program by clicking on its window
- focus LibreOffice / Premiere Pro to focus it

After these steps Hammerspoon detects it, which in turn results in HammerBar showing it on the taskbar.

Does that work for you?

That said, I'm close to releasing a new version that uses a different mechanism for getting the list of windows (which has worked for everything I use daily). I'm hoping to release it within a couple of weeks.

**Comment by daveedmee** [comment]
Hey, sorry for the very long delay. Some Adobe programs just work fine (Photoshop, Illustrator, InDesign). The problem still persists with After effects and Premiere Pro (and Media Encoder), even after focusing back from a different program to AE or PrPro or ME. 
For now I've just put the OSX dock on the right edge on the screen and got used to using that or alt tab to focus back to these "problematic" programs. 

I've also noticed that some programs like Microsoft Outlook appear twice in hammerbar, even with just one window being open. Also tooltips from hovering over browser icons for example seem to trigger Hammerbar to display them as if they were a second instance of said browser, just with an empty title inside the bar:

![grafik](https://github.com/glenreesor/HammerBar/assets/52132306/c1d082e5-770f-43b8-a541-2e531369e646)
(For example hovering over the bookmark icon inside firefox triggers this empty firefox instance in hammerbar.

For me personally these are just small caveats for a program that otherwise works so well and is a core element of my workflow but I figured I still let u know. Just came here to check if there's any updates in general :)

I'm not a programmer or anything so I don't know what you would need to troubleshoot (like logs or anything). I'll keep an eye on this repo this time so hopefully I will reply faster than 2 and so months :D

**Comment by glenreesor** [comment]
Hello! Now my time to apologize for the delay :smile: . I'm just finishing up the documentation for the latest version, which uses a different approach to getting the list of windows which I hope will solve your problems. Check back within a week and hopefully it will be released!

**Comment by glenreesor** [comment]
Hello again!
Version 1.0 is released and will hopefully address the issue of some programs not showing up in the task bar. If your `~/.hammerspoon/init.lua` is just this you shouldn't have to change anything after downloading the new version:
```lua
hs.loadSpoon("HammerBar")
spoon.HammerBar:start()
```

If you have other config like launchers or menus, please take a look at the updated README as the syntax has changed. Let me know how it goes!

**Comment by daveedmee** [comment]
Hey there!
Happy to see v1.0 released. Gave it a test spin and after adapting all the app launchers on my bar to the new syntax and changing around some colors I tested whether or not some of the programs show up on my taskbar.

The issue with tooltips showing up as windows on the taskbar still persists but is less noticeable now in my opinion thanks to the update interval.

Premiere Pro, After Effects and Media Encoder still don't show up on the Hammerbar, I don't know if there is an alternative way to get the windows to display or filter what kind of windows to display

**Comment by glenreesor** [comment]
That's too bad about the Adobe programs :frowning_face: -- I was expecting them to be fixed!

So a little background on my understanding of the concept of windows with Hammerspoon and MacOS. It seems that everything that can appear on the screen, like tooltips, notifications, even the HammerBar taskbar itself, are MacOS "windows". The challenge for HammerBar is to filter out the ones that aren't typically shown in a taskbar, but still keep everything else.

The HammerBar code relies on the window `role` property to decide what to show in the taskbar. If the role is `AXWindow` it will be shown, otherwise it won't. This is based on my own experimentation rather than fully understanding MacOS :smile: (I'm not a Mac developer -- I created this project since I'm forced to use Macs for work :roll_eyes: )

So it sounds like these Adobe windows have a different `role`. If you're up to some debugging, I've attached a HammerBar build that shows all "windows" except the HammerBar taskbar, and also logs debugging information to the Hammerspoon console. I'd be interested to see that debugging output and also whether the Adobe programs now show up for you.

(You'll need to change the extension to `.lua` since github doesn't allow attaching those types)

[init.txt](https://github.com/user-attachments/files/16729857/init.txt)

**Comment by daveedmee** [comment]
> I created this project since I'm forced to use Macs for work 🙄 )

That's why I came here :D
&nbsp;
> If you're up to some debugging, [...]

I am happy to help ^^
&nbsp;
[log.txt](https://github.com/user-attachments/files/16731737/log.txt)

Not quite sure how to make a log so I opened all windows at once and checked the time on the console and hastly copied the stuff inside the log window into vscode.
I hope it is any useful.

Around 18:33:33 - ::39 should be most useful because that's where all of them were opened.
(_**around line 296**_)

I've also noticed the different window styles around both of Illustrator and Premiere Pro. <img width="320" alt="Bildschirmfoto 2024-08-23 um 19 04 35" src="https://github.com/user-attachments/assets/aa236957-8aea-453b-ab22-b3144e11415f"> 

(Funnily enough, hammerbar sees the selection window of the screenshot app as a program with empty icon (blank white) and 'Window' as title. (also screenshot attached.)
<img width="421" alt="Bildschirmfoto 2024-08-23 um 19 29 58" src="https://github.com/user-attachments/assets/0fb9d511-5cb4-49c0-93c1-81f9d85901b7">


log confirms that 
Illustrator has the `AXWindow` role, whereas Premiere got the `AXLayoutArea` role.

Hope that helps ^^

**Comment by glenreesor** [comment]
Seeing the screenshot app as a "window" doesn't surprise me, as the concept of "window" seems to encompass a lot more things than we typically call windows :smile: .

As for grabbing the logs, there's no need to grab them immediately when the windows open, as the complete window list is getting logged each time HammerBar polls Hammerspoon; so any time after you've opened the windows (and the log has updated) would be fine. It might be easier to grab the logs by setting a longer update interval so the console isn't changing while you're trying to copy. Something like `setWindowListUpdateInterval(5)` might work well.

Based on your log, I see windows for:
- Adobe Premiere Pro 2004 -- as you point out, this has a role of `AXLayoutArea` which explains why it doesn't show up with the normal build of HammerBar
- Adobe Illustrator 2024 -- its role of `AXWindow` means it should show up for the normal build

Do both of ^^ show up in the taskbar with this debug build?

Your initial email also mentioned After Effects and Media Encoder but I don't see them in the log. Were they open at the time you grabbed the log?

**Comment by daveedmee** [comment]
> Your initial email also mentioned After Effects and Media Encoder but I don't see them in the log. Were they open at the time you grabbed the log?

No I didn't open them at that time but retrying now.

[log2.txt](https://github.com/user-attachments/files/16737368/log2.txt)

After Effects and Media Encoder seem to inherit the `AXLayoutArea` role as well.

> Do both of ^^ show up in the taskbar with this debug build?

The splash screens didn't but the main windows do. Premiere and the others don't have a window title so it's just icon and empty space. I've also tried creating new projects in all of them to see if they gain window titles from that but sadly they didn't. Thought it was worth a shot. Premiere and After Effects show up twice on Hammerbar. That is expected from my part as I have the preview window for both of them seperated to be displayed at my second monitor at work. 

<img width="1680" alt="Bildschirmfoto 2024-08-24 um 18 35 07" src="https://github.com/user-attachments/assets/168c5878-c64b-4125-bf13-16f936570f49">

**Comment by glenreesor** [comment]
Hey there,
Here's another debug build. It's different from the previous in the following ways:
- the debug info is only logged when you click the new smiley face button
- the debug info includes
  - window information as is currently used by v1.0
  - window information derived from a list of applications (similar to the v1.0 approach, but maybe some different info will be reported)
  - accessibility information for a number of different MacOS identifiers that could represent top-level windows (in particular `AXLayoutArea`), plus other accessibility info like title, which my research indicates may have a better chance of being populated :crossed_fingers: 

If you could grab two sets of debug info (both with all your adobe programs / windows open) -- one with no windows minimized and the other with all windows minimized, that would be great!

Hopefully we'll get some more info!
[init.txt](https://github.com/user-attachments/files/16756258/init.txt)

**Comment by daveedmee** [comment]
Man you're fast. I appreciate that
Here you go!

[log_minimized.txt](https://github.com/user-attachments/files/16758679/log_minimized.txt)
[log_opened.txt](https://github.com/user-attachments/files/16758680/log_opened.txt)

**Comment by glenreesor** [comment]
Looking through those logs, it looks like Adobe just isn't populating window title info :frowning: . A few things come to mind about how to easily identify windows when there are multiple ones with no title belonging to the same app:
- number the windows starting at 1 and use a title like "AppName 1" (e.g. "Adobe After Effects 1") -- although looking at that now, with long names like that there's the chance of truncating the string
- add a hover effect that shows a thumbnail on the window
- add the ability to manually specify a title by clicking (or right clicking) and being prompted for the title

Thoughts?

**Comment by daveedmee** [comment]
> Looking through those logs, it looks like Adobe just isn't populating window title info

Would it be possible to display the `appName` info as window title in case there isn't any `windowTitle` as some sort of fallback or would that cause problems with other programs?

About differenciating multiple windows belonging to the same app, I think that your idea of a hover effect displaying a thumbnail would be pretty much in line with how Windows and most Linux enviroments do it and I think this added familarity would also benefit the user experience.
(personally I don't mind how hammerbar does it now but I also use [AltTab](https://github.com/lwouis/alt-tab-macos) to replace the default mac window switcher)

Appreciate it!

**Comment by glenreesor** [comment]
Yep, showing the appName string as a fallback would work.

Another question for you. Right now hovering on the window button shows the full title, which I think is useful at times (although I'm not sure if Windows does this -- I'm on Linux :smile: ). If there's now a thumbnail..... Show both the non-truncated window title and the thumbnail? Perhaps have an option in `init.lua` to specify which you want to see?

**Comment by daveedmee** [comment]
> (although I'm not sure if Windows does this -- I'm on Linux 😄 )

afaik Windows shows the full version if there's enough space and the truncated version there isn't. thumbnails have the truncated version of the title displayed above (source: very annoyed friend of mine which I had him minimize his game just to see the thumbnail. I'm on linux as well lol.)


> If there's now a thumbnail..... Show both the non-truncated window title and the thumbnail?

Some browser tabs have very long titles which on the bar don't display in full either way (like this one! ) While the full title display on the tooltip is generally a good feature to have, I am unsure how the tooltip would look like if there's now a thumbnail added to it. Will thumbnails be bigger if the title is longer (scale with the length of the title/tooltip) to keep the aspect ratio of the window/screen? would there be a cutoff? 


> Perhaps have an option in `init.lua` to specify which you want to see?

As a user I generally love having options, but I don't know how hard it would be to implement them at all, I'm not a programmer or a hobbyist so to speak, just a very annoyed guy forced to use a macbook 😄

**Comment by glenreesor** [comment]
> source: very annoyed friend of mine which I had him minimize his game just to see the thumbnail.
:rofl: 

I'll do some experimenting with thumbnail on hover. In the mean time, I plan to do a small release that fixes the bugs you've identified (new window when taskbar is hidden, adobe programs missing). If you could run this pre-release to confirm those are indeed fixed and don't introduce any other weirdness, I'd appreciate it!

[init.txt](https://github.com/user-attachments/files/16827115/init.txt)

**Comment by glenreesor** [comment]
Thanks! I've created a new release (https://github.com/glenreesor/HammerBar/releases/tag/v1.0.1). This is identical to the one you tested, just with different version info embedded in the file.

I have some ideas for upcoming features and if you're game for providing input, I'll close this issue and create a new one specifically for that discussion :smile:

**Comment by daveedmee** [comment]
Hey again, I found a [similar issue](https://github.com/koekeishiya/yabai/issues/2039) with the same adobe programs with yabai (tiling window manager for macOS) and it seems that each window has a role and a subrole. So far we tackled the problem by just looking at the window role.

I am not sure if Hammerspoon provides a way to output the subrole in logs as well but I believe that this additional info is helpful in providing a solution that excludes things like tooltips from other programs from the taskbar or system overlays (like the screenshot tool for example) but also show all programs more reliably and would be something that was also mentioned in #7
