### ISSUE TITLE
How do I contribute to this project?

### ISSUE THREAD

**Issue by dinbtechit** [glenreesor/HammerBar#3]
Hi, I am a software developer. I would love to contribute to this project. But looking at the Package.json there are no dependencies. I am not a macOS developer. But I am trying to understand the architecture of this app and how it integrates with macOS and places the window on the bottom of the screen at all times. Any input would be massively helpful!

**Comment by glenreesor** [comment]
Hello!
You're right, the `package.json` is pretty empty! HammerBar is a "spoon" which gets run by [Hammerspoon](https://www.hammerspoon.org). Here's how things work:
- make sure you have Hammerspoon installed
- `npm install` to get the dev dependencies (mainly `typescript` and `typescript-to-lua`)
- `npm build` to transpile to typescript to lua. This will create `build/init.lua`
- create `~/.hammerspoon/Spoons/HammerBar/` and put the `init.lua` from the build step there
- create `~/.hammerspoon/init.lua`. Here's a simple one:

        hs.loadSpoon('HammerBar')
        spoon.HammerBar:start()

- restart Hammerspoon

The way HammerBar works is that it uses the Hammerspoon APIs for:
- drawing canvases on the bottom of the screen for the taskbar and buttons
- listening for click events
- getting a list of applications and corresponding windows

Does that help?

**Comment by glenreesor** [comment]
Hello Dinesh! I've just released a new version. Drop me a note if you have questions or suggestions.

**Comment by dinbtechit** [comment]
Hey Glen, absolutely. I will check it out and let you know. It would be nice to have a brew package for this.. 

Few things that I am looking for in a taskbar are...
- Multi-monitor support
- Show notifications for Teams, Slack, Discord, outlook, etc etc right in the taskbar.
- Hover over a taskbar item should show window preview
- clicking on the taskbar item - should toggle between maximize and minimize
- I personally don't care about the start menu. Just a launch pad is good enough for me.  

Also, I would like to implement [hammerspoon](https://www.hammerspoon.org/) in dart & flutter. I don't know how far that is possible.

**Comment by glenreesor** [comment]
Hey Dinesh,
- as you've no doubt seen, HammerBar has multi-monitor support
- I took a quick look at the Hammerspoon docs and it has support for notifications, but looks like it's only *creating* notifications, not intercepting notifications created by other apps (http://www.hammerspoon.org/docs/hs.notify.html)
- showing a window preview when hovering a taskbar item isn't in this release of HammerBar, but it looks like this should be possible
- clicking a taskbar item -- yep that works :smile: 
- the heavy lifting for HammerBar is done by Hammerspoon, so if you were to implement Hammerspoon in dart & flutter I suspect it would be pretty easy (relatively speaking) to add the required taskbar functionality and thus not even need HammerBar :smile: 

Looking forward to your thoughts about the current implementation.
