### ISSUE TITLE
CPU widget regularly shows over 100% usage even when in idle

### ISSUE THREAD

**Issue by daveedmee** [glenreesor/HammerBar#6]
I'm currently checking how many colors we need and activated all widgets the same way u described in the readme.

The CPU widgets regularly show numbers above 100%.
There seem to be an error in either the way the widget is programmed or initialized because while the CPU widgets shows usage of around 150-300% mac task manager stays around 20-25% 

<img width="176" alt="Bildschirmfoto 2024-10-04 um 13 15 06" src="https://github.com/user-attachments/assets/9f77762e-68e1-4398-9ed3-7da15246f14f">

Just missed when the CPU meter showed 435%

<img width="1273" alt="Bildschirmfoto 2024-10-04 um 13 23 57" src="https://github.com/user-attachments/assets/b7744f5f-8fc8-48eb-8fc0-4875afa94673">
Example of difference in usage percents

**Comment by glenreesor** [comment]
Ah, there are a couple of things going on here.

The first is that the method I put in the `README` was adding all the %cpu reported for individual processes. However I believe those percents are relative to a single CPU core -- i.e. if they add up to 100% you're using the equivalent of one CPU core. So the number of cores on your system will determine what the highest possible % that can be. For example my Mac has 4 cores so if it was completely using all cores, the CPU monitor in HammerBar would max out at 400%.

The second thing is I'm not entirely sure if those % values reported for individual processes include the "system" portion of the cpu load.

I've done some research, and I believe a better way to do this is using the `top` command which (a) reports as a percent of the total cores of the system, so the maximum will be a more sane 100% and (b) it separates user and system for you, so they just have to be summed.

So replacing the `getCurrentCpuUsage()` in your `init.lua` with the following should do the trick. Seems to work for me, but my mac is really slow so it can be tough to confirm if the values are matching the mac task manager. If it works for you, I'll update the `README`.

```
function getCurrentCpuUsage()
  local handle = io.popen('top -l 1')
  local result = handle:read('*a')
  handle:close()

  -- Extract the CPU user and sys values from the result
  local user, sys = result:match('CPU usage: (%d+%.%d+)%% user, (%d+%.%d+)%% sys')

  -- Convert to numbers and sum them
  local total_usage = tonumber(user) + tonumber(sys)

  return total_usage
end
```

**Comment by daveedmee** [comment]
I had to rename getCurrentCpuUsage to getCpuUsage but other than that it seems to work!
Important to note is that the function should be added at the top, I had it placed at the bottom of the init.lua and it didn't work ^^"

**Comment by glenreesor** [comment]
Oh, good catch! Thinking some more about this, I think I'll add a widget specifically for CPU usage as it would be a relatively common one.

**Comment by glenreesor** [comment]
New widget has been added and will be available in the next release. Or you can build the latest to get it now :smile: .

Use it like so:
```
    spoon.HammerBar.widgets:cpuMonitor({
        interval = 1,
        maxValues = 100,
        maxGraphValue = 100,
    }),
```
